INSERT OR IGNORE INTO pub_quiz_questions (id, text, answers, correct_answer_idx, game_type, is_player_specific)
VALUES
('q1', 'What is the capital of France?', '["London", "Berlin", "Paris", "Madrid"]', 2, 'normal', FALSE),
('q2', 'What is 7 times 8?', '["54", "56", "58", "60"]', 1, 'normal', FALSE),
('q3', 'What color is the sky on a clear day?', '["Red", "Blue", "Green", "Yellow"]', 1, 'normal', FALSE),
('q4', 'What is the largest planet in our solar system?', '["Saturn", "Jupiter", "Neptune", "Uranus"]', 1, 'normal', FALSE),
('q5', 'Who wrote Romeo and Juliet?', '["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"]', 1, 'normal', FALSE),
('q6', 'In what year did the Titanic sink?', '["1912", "1920", "1905", "1915"]', 0, 'normal', FALSE),
('q7', 'What is the smallest country in the world?', '["Monaco", "Liechtenstein", "Vatican City", "San Marino"]', 2, 'normal', FALSE),
('q8', 'Which planet is closest to the Sun?', '["Venus", "Mercury", "Earth", "Mars"]', 1, 'normal', FALSE),
('q9', 'What is the capital of Japan?', '["Seoul", "Beijing", "Tokyo", "Bangkok"]', 2, 'normal', FALSE),
('q10', 'How many sides does a hexagon have?', '["5", "6", "7", "8"]', 1, 'normal', FALSE),
('q11', 'What is the chemical symbol for gold?', '["Go", "Gd", "Au", "Ag"]', 2, 'normal', FALSE),
('q12', 'Which country has the most population?', '["India", "United States", "China", "Indonesia"]', 2, 'normal', FALSE),
('q13', 'What is the capital of Australia?', '["Sydney", "Melbourne", "Canberra", "Brisbane"]', 2, 'normal', FALSE),
('q14', 'In what year did World War 2 end?', '["1943", "1944", "1945", "1946"]', 2, 'normal', FALSE),
('q15', 'What is the largest ocean?', '["Atlantic", "Indian", "Arctic", "Pacific"]', 3, 'normal', FALSE),
('q16', 'How many continents are there?', '["5", "6", "7", "8"]', 2, 'normal', FALSE),
('q17', 'What is the capital of Spain?', '["Barcelona", "Valencia", "Madrid", "Seville"]', 2, 'normal', FALSE),
('q18', 'What is 15 divided by 3?', '["3", "5", "6", "7"]', 1, 'normal', FALSE),
('q19', 'What is the capital of Italy?', '["Milan", "Venice", "Rome", "Florence"]', 2, 'normal', FALSE),
('q20', 'How many bones are in the human body?', '["196", "206", "216", "226"]', 1, 'normal', FALSE),
('q21', 'What is the capital of Canada?', '["Toronto", "Vancouver", "Ottawa", "Montreal"]', 2, 'normal', FALSE),
('q22', 'What is H2O?', '["Hydrogen", "Oxygen", "Water", "Salt"]', 2, 'normal', FALSE),
('q23', 'In what year did the Eiffel Tower open?', '["1887", "1889", "1885", "1890"]', 1, 'normal', FALSE),
('q24', 'What is the capital of Germany?', '["Munich", "Hamburg", "Berlin", "Frankfurt"]', 2, 'normal', FALSE),
('q25', 'How many letters are in the English alphabet?', '["24", "25", "26", "27"]', 2, 'normal', FALSE),
('q26', 'What is the capital of Brazil?', '["Rio de Janeiro", "Brasilia", "Sao Paulo", "Salvador"]', 1, 'normal', FALSE),
('q27', 'What is Mount Everest?', '["A volcano", "A mountain", "A cave", "A plateau"]', 1, 'normal', FALSE),
('q28', 'What is the capital of Mexico?', '["Cancun", "Mexico City", "Acapulco", "Monterrey"]', 1, 'normal', FALSE),
('q29', 'How many days are in a leap year?', '["365", "366", "367", "368"]', 1, 'normal', FALSE),
('q30', 'What is the freezing point of water in Celsius?', '["0", "-1", "1", "-10"]', 0, 'normal', FALSE),
('q31', 'What is the capital of India?', '["Mumbai", "Delhi", "Bangalore", "Kolkata"]', 1, 'normal', FALSE),
('q32', 'Who invented the telephone?', '["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Benjamin Franklin"]', 1, 'normal', FALSE),
('q33', 'What is the capital of Egypt?', '["Cairo", "Giza", "Luxor", "Alexandria"]', 0, 'normal', FALSE),
('q34', 'What is 12 times 12?', '["144", "132", "156", "168"]', 0, 'normal', FALSE),
('q35', 'What is the capital of Sweden?', '["Gothenburg", "Malmo", "Stockholm", "Uppsala"]', 2, 'normal', FALSE),
('q36', 'How many minutes are in an hour?', '["50", "60", "70", "80"]', 1, 'normal', FALSE),
('q37', 'What is the capital of Thailand?', '["Chiang Mai", "Phuket", "Bangkok", "Pattaya"]', 2, 'normal', FALSE),
('q38', 'What is the speed of light?', '["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"]', 0, 'normal', FALSE),
('q39', 'What is the capital of Norway?', '["Bergen", "Stavanger", "Oslo", "Trondheim"]', 2, 'normal', FALSE),
('q40', 'How many strings does a violin have?', '["3", "4", "5", "6"]', 1, 'normal', FALSE),
('q41', 'What is the capital of Greece?', '["Thessaloniki", "Patras", "Athens", "Larissa"]', 2, 'normal', FALSE),
('q42', 'What is 25 plus 25?', '["40", "50", "60", "70"]', 1, 'normal', FALSE),
('q43', 'What is the capital of Portugal?', '["Porto", "Covilha", "Lisbon", "Setúbal"]', 2, 'normal', FALSE),
('q44', 'How many wheels does a tricycle have?', '["2", "3", "4", "5"]', 1, 'normal', FALSE),
('q45', 'What is the capital of Netherlands?', '["Rotterdam", "Utrecht", "Amsterdam", "The Hague"]', 2, 'normal', FALSE),
('q46', 'What is the largest desert in the world?', '["Sahara", "Arabian", "Gobi", "Kalahari"]', 0, 'normal', FALSE),
('q47', 'What is the capital of Poland?', '["Krakow", "Gdansk", "Warsaw", "Wroclaw"]', 2, 'normal', FALSE),
('q48', 'How many sides does a triangle have?', '["2", "3", "4", "5"]', 1, 'normal', FALSE),
('q49', 'What is the capital of Russia?', '["St Petersburg", "Kazan", "Moscow", "Novosibirsk"]', 2, 'normal', FALSE),
('q50', 'What is 100 divided by 4?', '["20", "25", "30", "40"]', 1, 'normal', FALSE),
('q51', 'What is the capital of Turkey?', '["Istanbul", "Izmir", "Ankara", "Bursa"]', 2, 'normal', FALSE),
('q52', 'What does DNA stand for?', '["Deoxyribonucleic Acid", "Dynamic Nuclear Acid", "Deoxyribose Nitrogen Acid", "Deoxynucleic Acid"]', 0, 'normal', FALSE),
('q53', 'What is the capital of Belgium?', '["Bruges", "Antwerp", "Brussels", "Ghent"]', 2, 'normal', FALSE),
('q54', 'How many vertices does a cube have?', '["6", "8", "10", "12"]', 1, 'normal', FALSE),
('q55', 'What is the capital of Austria?', '["Graz", "Salzburg", "Vienna", "Innsbruck"]', 2, 'normal', FALSE),
('q56', 'What is the deepest ocean trench?', '["Mariana Trench", "Tonga Trench", "Kuril Trench", "Philippine Trench"]', 0, 'normal', FALSE),
('q57', 'What is the capital of Switzerland?', '["Zurich", "Geneva", "Bern", "Basel"]', 2, 'normal', FALSE),
('q58', 'How many days are in February in a non-leap year?', '["28", "29", "30", "31"]', 0, 'normal', FALSE),
('q59', 'What is the capital of Hungary?', '["Debrecen", "Szeged", "Budapest", "Pecs"]', 2, 'normal', FALSE),
('q60', 'What is 9 times 9?', '["72", "81", "90", "99"]', 1, 'normal', FALSE),
('q61', 'What is the capital of Czech Republic?', '["Prague", "Brno", "Ostrava", "Plzen"]', 0, 'normal', FALSE),
('q62', 'What is the largest mammal in the world?', '["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"]', 1, 'normal', FALSE),
('q63', 'What is the capital of Romania?', '["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi"]', 0, 'normal', FALSE),
('q64', 'How many edges does a cube have?', '["9", "12", "15", "18"]', 1, 'normal', FALSE),
('q65', 'What is the capital of Bulgaria?', '["Sofia", "Plovdiv", "Varna", "Burgas"]', 0, 'normal', FALSE),
('q66', 'What is the highest mountain in Europe?', '["Mont Blanc", "Mount Elbrus", "Mount Rosa", "Dom"]', 1, 'normal', FALSE),
('q67', 'What is the capital of Croatia?', '["Split", "Rijeka", "Zagreb", "Zadar"]', 2, 'normal', FALSE),
('q68', 'How many meters are in a kilometer?', '["100", "500", "1000", "5000"]', 2, 'normal', FALSE),
('q69', 'What is the capital of Serbia?', '["Nis", "Novi Sad", "Belgrade", "Subotica"]', 2, 'normal', FALSE),
('q70', 'What is 3 squared?', '["6", "9", "12", "15"]', 1, 'normal', FALSE),
('q71', 'What is the capital of Ukraine?', '["Kharkiv", "Lviv", "Kyiv", "Odesa"]', 2, 'normal', FALSE),
('q72', 'What is the smallest ocean?', '["Arctic", "Atlantic", "Indian", "Pacific"]', 0, 'normal', FALSE),
('q73', 'What is the capital of Iceland?', '["Reykjavik", "Akureyri", "Hafnarfjordur", "Kópavogur"]', 0, 'normal', FALSE),
('q74', 'How many seconds are in a minute?', '["30", "60", "90", "120"]', 1, 'normal', FALSE),
('q75', 'What is the capital of Finland?', '["Tampere", "Turku", "Helsinki", "Oulu"]', 2, 'normal', FALSE);

